addSbtPlugin("com.eed3si9n"          % "sbt-assembly"         % "0.15.0")
addSbtPlugin("com.eed3si9n"          % "sbt-buildinfo"        % "0.12.0")
addSbtPlugin("org.typelevel"         % "sbt-tpolecat"         % "0.5.0")
addSbtPlugin("org.scalameta"         % "sbt-scalafmt"         % "2.4.2")
addSbtPlugin("com.github.sbt"        % "sbt-dynver"           % "5.0.1")
addSbtPlugin("com.snowplowanalytics" % "sbt-snowplow-release" % "0.3.1")
