addSbtPlugin("com.eed3si9n"              % "sbt-assembly"         % "2.1.5")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"        % "0.11.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"         % "0.1.17")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"         % "2.4.2")
addSbtPlugin("com.github.sbt"            % "sbt-dynver"           % "5.0.1")
addSbtPlugin("com.snowplowanalytics"     % "sbt-snowplow-release" % "0.3.1")
