name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v3
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'corretto'
          cache: sbt
      - uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.9.9
      - name: Check formatting
        run: sbt scalafmtCheckAll
      - name: Run unit tests
        run: sbt test
      - name: Run integration tests Kinesis
        run: sbt "project kinesisDistroless" IntegrationTest/test
      - name: Run integration tests PubSub
        run: sbt "project pubsubDistroless" IntegrationTest/test
